### ISSUE TITLE
Tensor Parallelism not working for API server

### ISSUE THREAD

**Issue by kjain1810** [S-LoRA/S-LoRA#44]
Hi

I am trying to run the API server with tensor parallelism (across either 2 or 4 GPUs). I am trying to run it with the following command:

```bash
python -m slora.server.api_server --max_total_token_num 10000 --model huggyllama/llama-7b --tokenizer_mode auto --swap --scheduler vtc_fair --no-lora --cost-func linear --max_req_input_len 4095 --max_req_total_len 4096 --tp 2 --predict-range 0 --lora tloen/alpaca-lora-7b-0 --lora tloen/alpaca-lora-7b-1 --lora tloen/alpaca-lora-7b-2 --fair-weights 1
```

However, the server fails to start with the following error message:
```text
========= Remote Traceback (2) =========
Traceback (most recent call last):
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/rpyc/core/protocol.py", line 369, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/rpyc/core/protocol.py", line 863, in _handle_call
    return obj(*args, **dict(kwargs))
  File "<path>/slora/server/router/model_infer/model_rpc.py", line 56, in exposed_init_model
    model_cfg = get_model_config(weight_dir, dummy=input_params.dummy)
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/rpyc/core/netref.py", line 152, in __getattr__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/rpyc/core/protocol.py", line 744, in sync_request
    return _async_res.value
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/rpyc/core/async_.py", line 111, in value
    raise self._obj
_get_exception_class.<locals>.Derived: cannot access 'dummy'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/rpyc/core/protocol.py", line 369, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/rpyc/core/protocol.py", line 879, in _handle_getattr
    return self._access_attr(obj, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/rpyc/core/protocol.py", line 806, in _access_attr
    name = self._check_attr(obj, name, param)
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/rpyc/core/protocol.py", line 796, in _check_attr
    raise AttributeError(f"cannot access {name!r}")
AttributeError: cannot access 'dummy'


 detoken init state: init ok
Exception ignored in: <function Socket.__del__ at 0x14d436474160>
Traceback (most recent call last):
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/zmq/sugar/socket.py", line 185, in __del__
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/zmq/_future.py", line 241, in close
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Socket.__del__ at 0x14d436474160>
Traceback (most recent call last):
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/zmq/sugar/socket.py", line 185, in __del__
  File "/opt/conda/envs/ptca/lib/python3.10/site-packages/zmq/_future.py", line 241, in close
TypeError: 'NoneType' object is not callable
```

Is this an issue with the way I am trying to run the server or an issue with the implementation?

Any help would be appreciated :)

**Comment by kjain1810** [comment]
I noticed Issue #27 and the plan a few months back. 

Has this code been tested and merged into main or do we need to work off the `tp_merge` branch in order to have tensor parallelism?

@Ying1123 tagging as you had replied back then, apologies if you are no longer maintaining this repo.
